//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pymes_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioLenceria
    {
        public int idcodigo { get; set; }
        public string nombreproducto { get; set; }
        public int cantidad { get; set; }
        public int valorunitario { get; set; }
        public int codigo { get; set; }
    }
}
